"""togglable voice permissions

Revision ID: 82415b4a1394
Revises: e822bf06c183
Create Date: 2026-06-13 10:45:43.713823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82415b4a1394'
down_revision: Union[str, Sequence[str], None] = 'e822bf06c183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_channels', sa.Column('manage_permissions', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_channels', 'manage_permissions')
    # ### end Alembic commands ###
