"""add owner_id

Revision ID: e822bf06c183
Revises: 202606060003
Create Date: 2026-06-13 07:40:26.561518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e822bf06c183'
down_revision: Union[str, Sequence[str], None] = '202606060003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_channels', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_voice_channels_owner_id'), 'voice_channels', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_channels_owner_id'), table_name='voice_channels')
    op.drop_column('voice_channels', 'owner_id')
    # ### end Alembic commands ###
